name: Android Build

on:
  release:
    types:
      - created

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Svelte app
        run: npm run build

      - name: Copy files to Android project
        run: npx cap sync android

      - name: Build and package APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Archive and upload APK
        uses: actions/upload-artifact@v3
        with:
          name: 'Android APK'
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk