name: Android Build

on:
  release:
    types:
      - created

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build Android APK
        run: |
          npm run build # Replace with your build command
          npx cap sync

      - name: Archive and upload APK
        uses: actions/upload-artifact@v3
        with:
          name: "Android APK"
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk