name: Build Native Apps

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build Svelte app
        run: yarn build

      - name: Copy files to Android project
        run: npx cap sync android

      - name: Build and package APK
        run: |
          cd android
          ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        id: sign_app_apk
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '30.0.2'

      - name: Rename Files
        run: |
          mv ${{steps.sign_app_apk.outputs.signedReleaseFile}} android/app/build/outputs/apk/release/vertretungsapp-release.apk

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk-artifacts
          path: android/app/build/outputs/apk/release/

  release:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Config Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: apk-artifacts

      - name: Create Release
        run: yarn release
